"""
Django settings for representlaw project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rt%0y&m1r2afx@y&s)5ws%5bcq9+!ogd_!&^gi8e2d1w-s5x#i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025

# Site ID
SITE_ID = 1


# Application definition

INSTALLED_APPS = [

    'django.contrib.sites',
    'django_comments',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party apps
    # 'captcha',
    'crispy_forms',
    'whoosh',
    'haystack',
    # my apps
    'myaccount',
    'website',
    "blog",

]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'representlaw.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'representlaw.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'website.context_processors.latest_post_footer',
                'website.context_processors.represent_telephone',

                # Renters
                'website.context_processors.allergy_uk',
                'website.context_processors.beekeepers',
                'website.context_processors.civil_legal_advice_url',
                'website.context_processors.crisis_url',
                'website.context_processors.find_council_url',
                'website.context_processors.gassafe_url',
                'website.context_processors.hmcts_fees_url',
                'website.context_processors.hmcts_form_ex160a_url',
                'website.context_processors.hmcts_form_n244_url',
                'website.context_processors.housing_ombudsman',
                'website.context_processors.hse_gas_tenants_url',
                'website.context_processors.nhs_carbon_monoxide_poisoning_url',
                'website.context_processors.pest_control_association',
                'website.context_processors.rentokil_signs_of_rats',
                'website.context_processors.rics_url',
                'website.context_processors.right_to_rent_gov',
                'website.context_processors.rspca_fleas',
            ],
        },
    },
]

"""TEMPLATE_CONTEXT_PROCESSORS = (
    'website.context_processors.latest_post_footer',
    'django.core.context_processors.auth',
    'website.context_processors.add_variable_to_context',
)"""


WSGI_APPLICATION = 'representlaw.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# WHOOSH_INDEX = os.path.join((BASE_DIR, 'whoosh/')

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn")

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    'C:/users/clark/desktop/development/representlaw/static',
    '/var/www/static/'
]

CRISPY_TEMPLATE_PACK = 'bootstrap3'
# CRISPY_TEMPLATE_PACK = 'uni_form'

# MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

"""ENV_PATH = os.path.abspath(os.path.dirname(__file__))
MEDIA_ROOT = os.path.join(ENV_PATH, 'media')"""

LOGIN_REDIRECT_URL = '/website/'
